modLoader="javafml"
loaderVersion="[40,)"
license="All Rights Reserved"

[[mods]]
modId="hpm"
version="2.6.6"
displayName="HalsPirateMod"
credits="Halbear1"
displayURL="https://halbear.net/"
logoFile="logo.png"
authors="Halbear"
description="a small ship mod containing 6 ships and a weapon"

[[dependencies.hpm]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.18.2]"
    ordering="NONE"
    side="BOTH"




